// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: proto/harbor/api.proto

package harbor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockData represents a block in the blockchain
type BlockData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Transactions  []*TransactionData     `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	PrevHash      string                 `protobuf:"bytes,4,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	StateRoot     string                 `protobuf:"bytes,6,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Validator     string                 `protobuf:"bytes,7,opt,name=validator,proto3" json:"validator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockData) Reset() {
	*x = BlockData{}
	mi := &file_proto_harbor_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockData) ProtoMessage() {}

func (x *BlockData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_harbor_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockData.ProtoReflect.Descriptor instead.
func (*BlockData) Descriptor() ([]byte, []int) {
	return file_proto_harbor_api_proto_rawDescGZIP(), []int{0}
}

func (x *BlockData) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BlockData) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *BlockData) GetTransactions() []*TransactionData {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BlockData) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *BlockData) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BlockData) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

func (x *BlockData) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

// TransactionData represents a transaction in the blockchain
type TransactionData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	From            string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To              string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount          uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Nonce           uint64                 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TransactionHash string                 `protobuf:"bytes,5,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Signature       string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionData) Reset() {
	*x = TransactionData{}
	mi := &file_proto_harbor_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionData) ProtoMessage() {}

func (x *TransactionData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_harbor_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionData.ProtoReflect.Descriptor instead.
func (*TransactionData) Descriptor() ([]byte, []int) {
	return file_proto_harbor_api_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionData) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransactionData) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransactionData) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionData) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TransactionData) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *TransactionData) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// ValidationResult represents the result of block validation
type ValidationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_proto_harbor_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_harbor_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_proto_harbor_api_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidationResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// BlockCreationRequest is a request to create a new block from the transaction pool
type BlockCreationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional previous block hash to build upon
	PrevBlockHash string `protobuf:"bytes,1,opt,name=prev_block_hash,json=prevBlockHash,proto3" json:"prev_block_hash,omitempty"`
	// Maximum number of transactions to include (0 means unlimited)
	MaxTransactions uint32 `protobuf:"varint,2,opt,name=max_transactions,json=maxTransactions,proto3" json:"max_transactions,omitempty"`
	// Address of the validator creating this block
	ValidatorAddress string `protobuf:"bytes,3,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlockCreationRequest) Reset() {
	*x = BlockCreationRequest{}
	mi := &file_proto_harbor_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCreationRequest) ProtoMessage() {}

func (x *BlockCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_harbor_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCreationRequest.ProtoReflect.Descriptor instead.
func (*BlockCreationRequest) Descriptor() ([]byte, []int) {
	return file_proto_harbor_api_proto_rawDescGZIP(), []int{3}
}

func (x *BlockCreationRequest) GetPrevBlockHash() string {
	if x != nil {
		return x.PrevBlockHash
	}
	return ""
}

func (x *BlockCreationRequest) GetMaxTransactions() uint32 {
	if x != nil {
		return x.MaxTransactions
	}
	return 0
}

func (x *BlockCreationRequest) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

// BlockCreationResponse contains the newly created block
type BlockCreationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *BlockData             `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCreationResponse) Reset() {
	*x = BlockCreationResponse{}
	mi := &file_proto_harbor_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCreationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCreationResponse) ProtoMessage() {}

func (x *BlockCreationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_harbor_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCreationResponse.ProtoReflect.Descriptor instead.
func (*BlockCreationResponse) Descriptor() ([]byte, []int) {
	return file_proto_harbor_api_proto_rawDescGZIP(), []int{4}
}

func (x *BlockCreationResponse) GetBlock() *BlockData {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *BlockCreationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// BlockValidationRequest is a request to validate a block
type BlockValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *BlockData             `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockValidationRequest) Reset() {
	*x = BlockValidationRequest{}
	mi := &file_proto_harbor_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockValidationRequest) ProtoMessage() {}

func (x *BlockValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_harbor_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockValidationRequest.ProtoReflect.Descriptor instead.
func (*BlockValidationRequest) Descriptor() ([]byte, []int) {
	return file_proto_harbor_api_proto_rawDescGZIP(), []int{5}
}

func (x *BlockValidationRequest) GetBlock() *BlockData {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_proto_harbor_api_proto protoreflect.FileDescriptor

const file_proto_harbor_api_proto_rawDesc = "" +
	"\n" +
	"\x16proto/harbor/api.proto\x12\fproto.harbor\"\xf0\x01\n" +
	"\tBlockData\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12A\n" +
	"\ftransactions\x18\x03 \x03(\v2\x1d.proto.harbor.TransactionDataR\ftransactions\x12\x1b\n" +
	"\tprev_hash\x18\x04 \x01(\tR\bprevHash\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"state_root\x18\x06 \x01(\tR\tstateRoot\x12\x1c\n" +
	"\tvalidator\x18\a \x01(\tR\tvalidator\"\xac\x01\n" +
	"\x0fTransactionData\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\x12)\n" +
	"\x10transaction_hash\x18\x05 \x01(\tR\x0ftransactionHash\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\"M\n" +
	"\x10ValidationResult\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x96\x01\n" +
	"\x14BlockCreationRequest\x12&\n" +
	"\x0fprev_block_hash\x18\x01 \x01(\tR\rprevBlockHash\x12)\n" +
	"\x10max_transactions\x18\x02 \x01(\rR\x0fmaxTransactions\x12+\n" +
	"\x11validator_address\x18\x03 \x01(\tR\x10validatorAddress\"k\n" +
	"\x15BlockCreationResponse\x12-\n" +
	"\x05block\x18\x01 \x01(\v2\x17.proto.harbor.BlockDataR\x05block\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"G\n" +
	"\x16BlockValidationRequest\x12-\n" +
	"\x05block\x18\x01 \x01(\v2\x17.proto.harbor.BlockDataR\x05block2\xbe\x01\n" +
	"\tHarborAPI\x12X\n" +
	"\vCreateBlock\x12\".proto.harbor.BlockCreationRequest\x1a#.proto.harbor.BlockCreationResponse\"\x00\x12W\n" +
	"\rValidateBlock\x12$.proto.harbor.BlockValidationRequest\x1a\x1e.proto.harbor.ValidationResult\"\x00B#Z!blockchain-simulator/proto/harborb\x06proto3"

var (
	file_proto_harbor_api_proto_rawDescOnce sync.Once
	file_proto_harbor_api_proto_rawDescData []byte
)

func file_proto_harbor_api_proto_rawDescGZIP() []byte {
	file_proto_harbor_api_proto_rawDescOnce.Do(func() {
		file_proto_harbor_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_harbor_api_proto_rawDesc), len(file_proto_harbor_api_proto_rawDesc)))
	})
	return file_proto_harbor_api_proto_rawDescData
}

var file_proto_harbor_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_harbor_api_proto_goTypes = []any{
	(*BlockData)(nil),              // 0: proto.harbor.BlockData
	(*TransactionData)(nil),        // 1: proto.harbor.TransactionData
	(*ValidationResult)(nil),       // 2: proto.harbor.ValidationResult
	(*BlockCreationRequest)(nil),   // 3: proto.harbor.BlockCreationRequest
	(*BlockCreationResponse)(nil),  // 4: proto.harbor.BlockCreationResponse
	(*BlockValidationRequest)(nil), // 5: proto.harbor.BlockValidationRequest
}
var file_proto_harbor_api_proto_depIdxs = []int32{
	1, // 0: proto.harbor.BlockData.transactions:type_name -> proto.harbor.TransactionData
	0, // 1: proto.harbor.BlockCreationResponse.block:type_name -> proto.harbor.BlockData
	0, // 2: proto.harbor.BlockValidationRequest.block:type_name -> proto.harbor.BlockData
	3, // 3: proto.harbor.HarborAPI.CreateBlock:input_type -> proto.harbor.BlockCreationRequest
	5, // 4: proto.harbor.HarborAPI.ValidateBlock:input_type -> proto.harbor.BlockValidationRequest
	4, // 5: proto.harbor.HarborAPI.CreateBlock:output_type -> proto.harbor.BlockCreationResponse
	2, // 6: proto.harbor.HarborAPI.ValidateBlock:output_type -> proto.harbor.ValidationResult
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_harbor_api_proto_init() }
func file_proto_harbor_api_proto_init() {
	if File_proto_harbor_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_harbor_api_proto_rawDesc), len(file_proto_harbor_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_harbor_api_proto_goTypes,
		DependencyIndexes: file_proto_harbor_api_proto_depIdxs,
		MessageInfos:      file_proto_harbor_api_proto_msgTypes,
	}.Build()
	File_proto_harbor_api_proto = out.File
	file_proto_harbor_api_proto_goTypes = nil
	file_proto_harbor_api_proto_depIdxs = nil
}
